

# Navigation Setting ======================
  # These records will appear in Header Navigation as Links.
  # The order of links would follow this order.
  #
  # @title: The title that would appears in links
  # @icon: Material Symbol that would appears in links (see https://fonts.google.com/icons)
  # @uri: The endpoint to route
  # @nestedRecords: Nested Links. Same as this structure. (Usually follows Categories)
# =========================================
NavRecords:

  - title: Home
    icon: home
    uri: /
    nestedRecords:

  - title: About
    icon: mood
    uri: /about
    nestedRecords:

  - title: Tags
    icon: sell
    uri: /tags
    nestedRecords:

  - title: Categories
    icon: format_list_bulleted
    uri: /categories
    nestedRecords:

    - title: Budgeting
      icon: abc
      uri: /categories/budgeting

    - title: Investing
      icon: abc
      uri: /categories/investing

    - title: Retirement
      icon: abc
      uri: /categories/retirement

    - title: Real Estate
      icon: abc
      uri: /categories/real-estate

    - title: Taxes
      icon: abc
      uri: /categories/taxes

    - title: Personal Finance
      icon: abc
      uri: /categories/personal-finance













