



# ==================================
NavBar_HorizonLinks:

  customComponentInjection: 
    # This component would be attached to the top of this component. (ex: 'CC_Example')

  showIcons: # true || false
    majorLinks: false
    subLinks: false


# ==================================
RouterLink_VstackNest:
  appearance: underlined
    # 'underlined' || 'filled'
  subLinkShrinkThreshold: 1350
    # Category Links Shrinks if the ViewWidth is smaller than this value. (Depends on Category counts)









