

shape:
  roundness: 0
    # 0 || 1 || 2


# ==========================================
theme: # ===================================

  colorScheme:
    appearance: auto
    lightThemeClass: theme--default-light
    darkThemeClass: theme--default-dark

  browserContainerColors:
  # The color that would be applied to Safari container colors on Apple Devices. 
  # Corresponds to theme-class-names in `../styles/_colors.scss`
    theme--default-light: '#ffffff'
    theme--default-dark: '#f0f0f0'


