

navBar:
  navBarLinkType: underlined
    # 'underlined' || 'filled'
  showIcons: # true || false
    majorLinks: false
    subLinks: false
  subLinkShrinkThreshold: 1350
    # Category Links Shrinks if the ViewWidth is smaller than this value. (Depends on Category counts)



shape:
  roundness: 0
    # 0 || 1 || 2


theme:

  colorScheme:
    appearance: auto
    lightThemeClass: theme--default-light
    darkThemeClass: theme--default-dark

  browserContainerColors:
    theme--default-light: '#f0f0f0'
    theme--default-dark: '#f0f0f0'

